from setuptools import setup, find_packages

setup(
    name='AudioX',
    version='0.2.0',
    url='https://github.com/ZeyueT/AudioX.git',
    author='AudioX, HKUST',
    description='Training and inference tools for generative audio models from AudioX',
    packages=find_packages(),  
    install_requires=[
        'aeiou',
        'alias-free-torch',
        'auraloss',
        'descript-audio-codec',
        'eva-decord',
        'einops',
        'einops_exts',
        'ema-pytorch',
        'encodec',
        'gradio',
        'gradio_client',
        'huggingface_hub',
        'importlib-resources',
        'k-diffusion',
        'laion-clap',
        'local-attention',
        'pandas',
        'pedalboard',
        'prefigure',
        'pytorch_lightning', 
        'PyWavelets',
        'safetensors',
        'sentencepiece',
        'torch>=2.0.1',
        'torchaudio>=2.0.2',
        'torchmetrics',
        'tqdm',
        'transformers',
        'v-diffusion-pytorch',
        'vector-quantize-pytorch',
        'wandb',
        'webdataset',
        'x-transformers',
    ],

)